<!--[if gte mso 9]>
	<xml>
	 <o:DocumentProperties>
	  <o:Author><%=session("userid")%></o:Author>
	  <o:LastAuthor></o:LastAuthor>
	  <o:Revision>3</o:Revision>
	  <o:TotalTime>50</o:TotalTime>
	  <o:LastPrinted><%=now%></o:LastPrinted>
	  <o:Created><%=now%></o:Created>
	  <o:LastSaved><%=now%></o:LastSaved>
	  <o:Pages>1</o:Pages>
	  <o:Words>1749</o:Words>
	  <o:Characters>9974</o:Characters>
	  <o:Company>臺灣銀行股份有限公司</o:Company>
	  <o:Lines>83</o:Lines>
	  <o:Paragraphs>23</o:Paragraphs>
	  <o:CharactersWithSpaces>11700</o:CharactersWithSpaces>
	  <o:Version>11.8132</o:Version>
	 </o:DocumentProperties>
	 <o:CustomDocumentProperties>
	  <o:BrId dt:dt="string"><%=session("brid")%></o:BrId>
	  <o:UserId dt:dt="string"><%=session("userid")%></o:UserId>
	  <o:FileTime dt:dt="date"><%=now%></o:FileTime>
	 </o:CustomDocumentProperties>
	 <o:OfficeDocumentSettings>
	   <o:TargetScreenSize>1024x768</o:TargetScreenSize>
	   <o:PixelsPerInch>72</o:PixelsPerInch>
	 </o:OfficeDocumentSettings>	 
	</xml>
<![endif]-->

<!--[if gte mso 9]>
	<xml>
	 <w:WordDocument>
	  <w:SpellingState>Clean</w:SpellingState>
	  <w:PunctuationKerning/>
	  <w:DisplayHorizontalDrawingGridEvery>0</w:DisplayHorizontalDrawingGridEvery>
	  <w:DisplayVerticalDrawingGridEvery>2</w:DisplayVerticalDrawingGridEvery>
	  <w:ValidateAgainstSchemas/>
	  <w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>
	  <w:IgnoreMixedContent>false</w:IgnoreMixedContent>
	  <w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>
	  <w:Compatibility>
	   <w:SpaceForUL/>
	   <w:BalanceSingleByteDoubleByteWidth/>
	   <w:DoNotLeaveBackslashAlone/>
	   <w:ULTrailSpace/>
	   <w:DoNotExpandShiftReturn/>
	   <w:AdjustLineHeightInTable/>
	   <w:BreakWrappedTables/>
	   <w:SnapToGridInCell/>
	   <w:WrapTextWithPunct/>
	   <w:UseAsianBreakRules/>
	   <w:DontGrowAutofit/>
	   <w:UseFELayout/>
	  </w:Compatibility>
	  <w:BrowserLevel>MicrosoftInternetExplorer4</w:BrowserLevel>
	 </w:WordDocument>
	</xml>
<![endif]-->

<!--[if gte mso 9]>
	<xml>
	 <w:LatentStyles DefLockedState="false" LatentStyleCount="156">
	 </w:LatentStyles>
	</xml>
<![endif]-->

<!--[if !mso]>
	<object classid="clsid:38481807-CA0E-42D2-BF39-B33AF135CC4D" id=ieooui></object>
	<style>
st1\:*{behavior:url(#ieooui) }
</style>
<![endif]-->

<!--[if gte mso 10]>
<style>
 /* Style Definitions */
 table.MsoNormalTable
	{mso-style-name:表格內文;
	mso-tstyle-rowband-size:0;
	mso-tstyle-colband-size:0;
	mso-style-noshow:yes;
	mso-style-parent:"";
	mso-padding-alt:0cm 5.4pt 0cm 5.4pt;
	mso-para-margin:0cm;
	mso-para-margin-bottom:.0001pt;
	mso-pagination:widow-orphan;
	font-size:10.0pt;
	font-family:"Times New Roman";
	mso-fareast-font-family:"Times New Roman";
	mso-ansi-language:#0400;
	mso-fareast-language:#0400;
	mso-bidi-language:#0400;}
table.MsoTableGrid
	{mso-style-name:表格格線;
	mso-tstyle-rowband-size:0;
	mso-tstyle-colband-size:0;
	border:solid windowtext 1.0pt;
	mso-border-alt:solid windowtext .5pt;
	mso-padding-alt:0cm 5.4pt 0cm 5.4pt;
	mso-border-insideh:.5pt solid windowtext;
	mso-border-insidev:.5pt solid windowtext;
	mso-para-margin:0cm;
	mso-para-margin-bottom:.0001pt;
	line-height:150%;
	mso-pagination:none;
	mso-layout-grid-align:none;
	text-autospace:none;
	font-size:10.0pt;
	font-family:"Times New Roman";
	mso-ansi-language:#0400;
	mso-fareast-language:#0400;
	mso-bidi-language:#0400;}
@page Section1
{
	mso-gutter-margin:0.75cm;
}
div.Section1
{page:Section1;}
</style>
<![endif]-->

