<Script lang="JavaScript" src="<%=com.Azion.EloanUtility.UIUtility.getRootPath() + "/js/JSUtil.js"%>"></Script>
<!-- 需畫面列印 請include 『printscript.inc』  -->
<script lang="JavaScript" src="<%=com.Azion.EloanUtility.UIUtility.getRootPath() + "/js/KeyCheck.js"%>"></script>
<script type="text/javascript" language="javascript" src="<%=com.Azion.EloanUtility.UIUtility.getRootPath() + "/js/jquery-1.7.1.min.js"%>"></script>
<script language="JavaScript" src="<%=com.Azion.EloanUtility.UIUtility.getRootPath() + "/js/json2.js"%>"></script>