<link href="<%=com.Azion.EloanUtility.UIUtility.getRootPathClient() + "/css/ENbot.css"%>" rel="StyleSheet" media="screen" />
 <!-- Bootstrap Core CSS -->
<link href="<%=com.Azion.EloanUtility.UIUtility.getRootPathClient() + "/css/bootstrap.css"%>" rel="stylesheet" type="text/css" />
   <!-- Custom CSS -->
<link href="<%=com.Azion.EloanUtility.UIUtility.getRootPathClient() + "/css/portfolio-item.css"%>" rel="stylesheet" type="text/css" />
<link href="<%=com.Azion.EloanUtility.UIUtility.getRootPathClient() + "/css/font-awesome.min.css"%>" type="text/css" />
<link href="<%=com.Azion.EloanUtility.UIUtility.getRootPathClient() + "/css/animated.css"%>" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400italic,400,600,700'   rel='stylesheet' type='text/css' />
   <!-- Script -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

