<ASP:PANEL id="ErrorMsg" Runat="server" Visible="False">
<div class="container">
<div class="row">
<div class="col-md-12">
	<div class="alert alert-danger alert-dismissible" role="alert">
	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	<strong>注意!</strong> <asp:label id="lblErrorMsg" runat="server" ForeColor="black" EnableViewState="False"></asp:label>
</div>

</div>	
</div></div>


</ASP:PANEL>
