<ASP:PANEL id="ErrorMsg" Runat="server" Visible="False">
	<TABLE cellSpacing="0" cellPadding="0" width="100%" align="center" border="0">
		<TR align="center">
			<TD class="mtr" align="left" width="100%" colSpan="2" height="50" valign="top" style="background:transparent">
			 	 <asp:label id="lblErrorMsg" runat="server" style="font-size:16pt;font-weight:bold" ForeColor="red" EnableViewState="False"></asp:label>
			</TD>
		</TR>
	</TABLE>
</ASP:PANEL>