<!-- 需畫面列印 請include 『printscript.inc』  -->
<Script lang="JavaScript" src="<%=com.Azion.EloanUtility.UIUtility.getRootPath() + "/js/jquery.js"%>"></Script>
<Script lang="JavaScript" src="<%=com.Azion.EloanUtility.UIUtility.getRootPath() + "/js/jquery.validate.js"%>"></Script>
<Script lang="JavaScript" src="<%=com.Azion.EloanUtility.UIUtility.getRootPath() + "/js/jquery.validate.extension.js"%>"></Script>
